---
title: 'Probability and Statistics: Assignment 5'
author: ''
date: '2017-09-13'
slug: probability-and-statistics-assignment-5
categories: []
tags: []
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1.  Use the [code](/courses/MATH333/activities/joint-distribution-tables/) I provided on the course website to reproduce the results of Exercise 4.1. Add your own comments as the author instructs in the problem statement.

1.  Exercise 4.6. Formatting tables with RMarkdown is easy, so you can type up the answer without too much trouble.

1.  A certain drug test has sensitivity 0.98 and specificity 0.90. 

    a.  Which conditional probabilities do these represent?
    
    a.  It is known that 10% of a certain population use this drug. If an individual from the population tests positive, what is the probability that they are a user?
    
    a.  This individual is re-tested and the result is negative. What is the (updated) probability that they are a user?
    
1.  Follow the exact instructions for exercise 5.2 but applied to the drug testing situation from the previous problem.

1.  Follow the exact instructions for exercise 5.3 but applied to the drug testing situation from the previous problem.