---
title: 'Probability and Statistics: Assignment 10'
author: ''
date: '2017-10-30'
slug: probability-and-statistics-assignment-10
categories: []
tags: []
---

1.  Consider a certain population of mule deer.

    a.  Suppose we know that 12% of the males have chronic wasting disease. We plan to collect a sample of 24 males. Graph the appropriate pmf.
    
    a.  Suppose now we obtain a sample of 24 males, 4 of which are infected. Given the prevalence is 12%, what is the probability of this observation? Calculate this using both the formula and the appropriate `R` function.
    
    a.  Suppose now that we don't know the prevalence. What is the likelihood that the prevalence is 12% in light of the data?
    
    a.  What is the likelihood that the prevalence is 21% in light of the data?
    
    a.  Graph the likelihood profile for the given data and include "dots" showing the two cases 12% and 21%.
    
    a.  What is the maximum likelihood estimate of the prevalence in light of the data? Show this analytically.
    
1.  Consider a certain pond tadpole population.

    a.  Suppose we know that the average number of tadpoles per liter in the pond is 23. Graph the appropriate pmf.
    
    a.  Suppose now we obtain a sample that contains 14 tadpoles. Given the average number of tadpoles per liter is 23, what is the probability of this observation? Calculate this using both the formula and the appropriate `R` function.
    
    a.  Suppose we obtain another, independent sample that contains 34 tadpoles. Given the average number of tadpoles per liter is 23, what is the probability of (all of) our data?
    
    a.  Suppose now that we don't know the average number of tadpoles per liter. What is the likelihood that the average number of tadpoles per liter is 23 in light of the data?
    
    a.  Graph the likelihood profile for the given data.
    
    a.  What is the maximum likelihood estimate of the average number of tadpoles per liter in light of the data? Show this analytically.
    
1.  Consider a certain (meta)population of ponds containing frogs. We want to make inference about the average rate of extinction for a pond.

    a.  Suppose we observe an extinction after 10 days. Graph the likelihood profile for the given data.
    
    a.  What is the maximum likelihood estimate of the average extinction rate in light of the data? Show this analytically.
    
    a.  Suppose we next observe an extinction after 18 days. Graph the likelihood profile for (all of) the given data.
    
    a.  What is the maximum likelihood estimate of the average extinction rate in light of (all of) the data? Show this analytically.