---
title: "Syllabus: Numerical Methods"
highlight: 'FALSE'
weight: 222003
---

## Professor {#top}

Jason Bintz  
Office: Paine 209A  
E-Mail: jason.bintz@houghton.edu  
<https://jasonbintz.rbind.io> 
                                                      
## Index {#top}

[Course Description](#description)  
[Textbook](#text)  
[Calculator](#calc)  
[Exams](#exams)  
[Homework](#homework)  
[Homework Guidelines](#guidelines)  
[Grading](#grading)  
[Academic Honesty](#honesty)  
[Accomodations](#accomodations)  
[Resources](#resources)  
[Time Commitment](#time)    

-------------------------------------------------------------------

## Course Description {#description}



[**Return to Index**](#top)

-------------------------------------------------------------------

## Textbooks {#text}



[**Return to Index**](#top)

-------------------------------------------------------------------

## Calculator {#calc}



[**Return to Index**](#top)

------------------------------------------------------------------------

## Exams {#exams}

There will be ____ in-class exams during the semester. Make up exams will only be given in extenuating circumstances; prior arrangements must be made if at all possible. Do not make travel plans that require you to miss a scheduled exam. The college final exam schedule can be found [here](http://www.houghton.edu/registrar/final-exam-schedules/).

[**Return to Index**](#top)

------------------------------------------------------------------------

## Homework {#homework}



[**Return to Index**](#top)

------------------------------------------------------------------------

## Homework Guidelines {#guidelines}



[**Return to Index**](#top)

------------------------------------------------------------------------

## Grading {#grading}

Problem sets will be worth around 30% of your grade, WebAssign assignments 20%, exams 30%, and the final exam 20%. I reserve the right to change the grading distribution. Final letter grades will be assigned based on the scale below at a minimum (i.e., if you earn a 94% overall in the course, your final grade will be at least an A-): 

| | | | | | | | |
|:------|:------|:------|:------|:------|:------|:------|:------|
| A | ≥ 96% | B | 87–91% | C | 74–82% | D | 67–69% | 
| A- | 94–95% | B- | 85–86% | C- | 72–73% | D- | 65–66% |
| B+ | 92–93% | C+ | 83–84% | D+ | 70–71% | F | <65%  |

[**Return to Index**](#top)

------------------------------------------------------------------------

## Academic Honesty {#honesty}

Students are expected to be familiar with and comply with the college statement on academic honesty found [here](http://www.houghton.edu/2014-2015-catalog/academic-information/policies/).

[**Return to Index**](#top)

------------------------------------------------------------------------

## Accomodations {#accomodations}

If you have a disability and need accommodations in this course, please discuss it with the Director of the Center for Academic Success and Advising, Ms. Sharon Mulligan. Her office is in the CASA suite (in room 222 in the Chamberlain Center) and the CASA extension is 2610. Please let me know how I can assist you as well.

[**Return to Index**](#top)

------------------------------------------------------------------------

## Resources {#resources}

Some possible places to find assistance:

- Fellow students
- Help sessions
- Office hours
- The internet; there are several good websites with calculus help that you are welcome to use for additional explanations, but you may not use the internet for solutions

------------------------------------------------------------------------

## Time Commitment {#time}

In accordance with the guidelines of 2–3 hours of work for each credit hour for a course, the well-prepared student should spend approximately 8–12 hours of work per week beyond the time spent in class. If you find that you are spending significantly more time than this, please let me know so that I can help you be more efficient or adjust the workload. If you are spending less time than this, you may not be investing enough time to learn well.
